name: publish

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn build
            - run: ls -la
            - uses: actions/upload-artifact@v2 # save the files use for the package
              with:
                  name: npm_pkg
                  path: |
                      README.md
                      package.json
                      src/
                      lib/

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn lint

    publish:
        runs-on: ubuntu-latest
        needs: [build, lint]
        steps:
            - uses: actions/download-artifact@v2 # download files used in build step
              with:
                  name: npm_pkg
            - uses: actions/setup-node@v1
              with:
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn install --prod
            - uses: pascalgn/npm-publish-action@v1
              with:
                  workspace: '.'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
